### ISSUE TITLE
Image hosting with IPFS [3 days]

### ISSUE THREAD

**Issue by jimcky** [likecoin/puttyimages-web#1]
Needed: N/A
Needed by #2
Needed by #3
Needed by #19
Needed by #22

- [ ] Upload image to IPFS
- [ ] Pin Image in PuttyImage's IPFS index
- [ ] Support unpinning image in puttyimage's IPFS index
- [ ] retrieve image by fingerprint / asset ID

Created from Aha! https://oursky.aha.io/features/PUT-21

**Comment by rickmak** [comment]
This issue will need to create model and confirm with the IPLD format written here: https://github.com/likecoin/puttyimages-web/wiki/IPLDFormat

**Comment by rickmak** [comment]
In addition , we need to have the API on how we sign the IPLD on the LikeChain.

**Comment by mckingho** [comment]
@rickmak We have not finalized the ipld part. For IPFS task, we expect it is up to hosting and basic service integration. Additional API call such as putting ipld object can be added when needed.

**Comment by mckingho** [comment]
@rickmak For IPFS api, please give me the function details after you finish it. In uploading image task, api needed are file add, dag put and pin add. 
Any missing info you want for this part?
