### ISSUE TITLE
Masonry grids for showing image list

### ISSUE THREAD

**Issue by jimcky** [likecoin/puttyimages-web#22]
- [ ] load 5 rows of image results per page
- [ ] Adjust masonry grid sizes upon window resize (tech lead please suggest usable library / approach for this feature)
- [ ] shows load more button at the bottom, clicking it would load an additional 15 images (next page)
- [ ] when image is hovered (desktop), shows uploader, liked stat and use image button on an translucent black overlay 
- [ ] when image is tapped for the first time (mobile), shows uploader, liked stat and use image button on an translucent black overlay , opens the image detail modal if user tapped on the empty space again
- [ ] (Desktop) when user clicked on the empty space of the image grid overlay (trigged by hovering), shows the image details modal
- [ ] Image cells max length = 2x width
- [ ] if image is smaller than the grid cell, fill the unused space with grey background

Created from Aha! https://oursky.aha.io/features/PUT-20

**Comment by rickmak** [comment]
Today pick the lib.

**Comment by rickmak** [comment]
Propose:

Use pure CSS implementation, refs: http://w3bits.com/flexbox-masonry/

And fallback to grid view for browser not support flexbox.

Thought?

**Comment by nwingt** [comment]
Confirm fallback using grid like Instagram for IE
