### ISSUE TITLE
Add new image page - backend

### ISSUE THREAD

**Issue by jimcky** [likecoin/puttyimages-web#3]
Need #1 
Needed by #13 
Needed by #11 

Error message:

https://docs.google.com/spreadsheets/d/1NAbJdl7Pti4D\_lhzBd1A\_C9pC25L4nlouZVdI28hvOU/edit#gid=0

- [ ] Can be accessed when user goes to a certain URL
- [ ] Checks if metamask wallat app is available and is linked to a recognized likecoin user
- [ ] When file is uploaded, shows a preview of the image
- [ ] User can use a file picker the upload file
- [ ] When user selected the file, validate the image and check if it matches the requirement of puttyimage assets
    Size, file format etc...
    
- [ ] Reject files that doesn't match the requirements and shows an error message
- [ ] Shows form for entering information for the image
    - Image description (optional)
    
    - tags (must enter at least 1)
    
    - Image license (must select)
    
       -  CC0
    
- [ ] Shows disclaimer and terms to link
- [ ] require users to explicitly click the "I accept the terms and conditions of puttyimage" checkbox before the image can be uploaded
- [ ] Disable the button if user haven't checked the accept terms checkbox
- [ ] When user clicks the Upload image now button, validates the input in the form, shows error message next to field where necessary
- [ ] Checks for similar image and warn user they should only upload original image
- [ ] Check if identical images had been uploaded before and warn user that they should only upload original images they owned
- [ ] only support png & jpg
- [ ] no minimal size, max size allowed = 10Mb
- [ ] require user to choose a license for the image being uploaded, can be one of 4
    cc0, 
    
    cc-by,
    
    cc-by-sa,
    
    cc-by-nd
    
- [ ] shows a hint under the license input: "Learn more about %license name", link to corresponding page of explaining the license
    [cc0](https://creativecommons.org/share-your-work/public-domain/cc0/)
    
    [cc-by](https://creativecommons.org/licenses/by/4.0/),
    
    [cc-by-sa](https://creativecommons.org/licenses/by-sa/4.0/),
    
    [cc-by-nd](https://creativecommons.org/licenses/by-nd/4.0/)
    
- [ ] user must input at least one tag
- [ ] tag must be 2 - 20 characters
- [ ] up to 5 tags can be added 
- [ ] must select a license to upload
- [ ] if all checks pass, call API, upload image to IPFS and register the record on blockchain
- [ ] generate and register embed code once upload is completed

Created from Aha! https://oursky.aha.io/features/PUT-15

**Comment by williamchong007** [comment]
@nwingt @mckingho please try to actually `work on` this card and see what kind of problem you might encounter

**Comment by mckingho** [comment]
`Checks for similar image and warn user they should only upload original image`
should not be completed in phrase 1.

**Comment by nwingt** [comment]
@williamchong007 Is `Checks if MetaMask wallat app is available and is linked to a recognized likecoin user` related to #8?

**Comment by williamchong007** [comment]
probably, also it involved calling a like.co api that does not exist yet @nwingt

**Comment by nwingt** [comment]
@williamchong007 Maybe refactor EthHelper into common modules?

**Comment by williamchong007** [comment]
no idea on how to do that elegantly but it would be nice @nwingt

**Comment by rickmak** [comment]
Please add `in progress` label to avoid duplicate effort on the same issue.
