### ISSUE TITLE
Add plugin:vue/essential to eslint

### ISSUE THREAD

**Issue by rickmak** [likecoin/puttyimages-web#34]

**Comment by inDream** [comment]
@nwingt Any preferred attributes order?
https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/attributes-order.md

**Comment by inDream** [comment]
@nwingt thanks

**Comment by inDream** [comment]
@nwingt How about `vue/name-property-casing` & `vue/attribute-hyphenation`:
https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/name-property-casing.md
https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/attribute-hyphenation.md
