### ISSUE TITLE
LikeCoin user related model planning & implementation

### ISSUE THREAD

**Issue by jimcky** [likecoin/puttyimages-web#37]
Needed #8
Needed by #15
Needed by #21
Needed by #19

**Comment by mckingho** [comment]
To query like.co or its provided endpoint to get user info by wallet address. It requires user sign.
The response contains likecoin id, display name, email.

**Comment by jimcky** [comment]
- [ ] Log user in after metamask check

**Comment by rickmak** [comment]
refs: https://github.com/likecoin/puttyimages-web/wiki/LoginFlow

**Comment by mckingho** [comment]
The jwt content is 
```
{ likecoinId, wallet, createdTs }
```

**Comment by rickmak** [comment]
I think we will want to add a `expiryTs` for remember me.

I propose to have a default expiryTs now implement without the remember me.

**Comment by mckingho** [comment]
@rickmak there is a `expiresIn` option in jwt sign. It is validated by the used jwt library. Does it enough for you?
