### ISSUE TITLE
should `plugins/ipfs` be actually in `/plugins`?

### ISSUE THREAD

**Issue by williamchong007** [likecoin/puttyimages-web#40]
it is neither a nuxt plugin used by both server or client, nor needed by client as a plugin for `Vue.use`
should server side only code be moved into `/server` ? not like client will need to call ipfs api directly in the future

**Comment by rickmak** [comment]
Yes, it should not in `plugin`. We are moving it at here: https://github.com/oursky/puttyimages-web/pull/25

**Comment by rickmak** [comment]
Landed at 7a8190f
