### ISSUE TITLE
Making Dockerfile.production multi stage and only install production node_modules

### ISSUE THREAD

**Issue by rickmak** [likecoin/puttyimages-web#42]
We should have:

First stage: install all dependency and build the releasable code
Second stage: copy the build file in first stage and only install node_modules required for production run

refs: https://docs.docker.com/develop/develop-images/multistage-build/

**Comment by rickmak** [comment]
Close via e34e2f7

**Comment by williamchong007** [comment]
that commit were probably missing a `npm install --only=production` related stage? not sure @inDream

**Comment by rickmak** [comment]
Yes you are right, the Dockerfile is running with dev node_modules.

**Comment by rickmak** [comment]
`node:10-slim` don't have git installed and will result in following error on `npm install --only=production`

```
npm ERR! undefined ls-remote -h -t ssh://git@github.com/dignifiedquire/webcrypto-shim.git
npm ERR! 
npm ERR! undefined
npm ERR! No git binary found in $PATH
```

**Comment by rickmak** [comment]
Another approach is to run `npm prune --production` in release layer.

BTW, does the node-gyp related module will work after coipying? Does @inDream confirmed?
