### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by jimcky** [likecoin/puttyimages-web#5]
Needed: N/A
Needed by: EVERYTHING - LET THERE BE LIGHT

- [x] Front end and SSR setup with Nuxt.js and express
    - Bootstrap Nuxt.js with Vue SSR /w Vuex  
    - Express with Nuxt.js
    
- [x] Backend setup - dockerized approach
    - Express with sequelizejs  
    - Setup Dockerfile  
    - Setup the docker-compose on IPFS, posgreSQL
- [ ] Front end deployment for IPFS
- [ ] Backend deployment powered by docker

Created from Aha! https://oursky.aha.io/features/PUT-5

**Comment by williamchong007** [comment]
Reference:
https://github.com/williamchong007/nuxt-express-template-airbnb

**Comment by jimcky** [comment]
Rick

IPFS
Docker
Look into backend deployment

----

William, setup DB

**Comment by williamchong007** [comment]
er not sure what kind of db setup you need, and I happen to have more exp on any of the above 3 items than prosgret 😂

**Comment by jimcky** [comment]
@williamchong007 oh, it's for William, our colleague at Oursky XD...

**Comment by williamchong007** [comment]
namespace pollution☠️

**Comment by williamchong007** [comment]
@rickmak  if possible, please update the npm dependencies from the scaffold to latest, both to avoid `npm audit` complaining and to lower future upgrade cost
thanks
