### ISSUE TITLE
Metamask / Trust Wallet check

### ISSUE THREAD

**Issue by jimcky** [likecoin/puttyimages-web#8]
Needed: N/A
Needed by #13 

- [ ] Check if metamask is available when user starts a new browsing session (could be home page or other pages)
- [ ] Shows a prompt to tell user to install / connect to metamask if it's not installed / found
- [ ] If user dismisses the prompt, do not warn the user for this session unless the user attempts to start the upload image flow 
- [ ] Always check if metamask information is still available when user attempts to upload an image
- [ ] While the modal is shown, user shouldn't be able to interact with page elements under the backdrop overlay
- [ ] For mobile apps, check if Trust wallet app is installed and try to authenticate using it

Created from Aha! https://oursky.aha.io/features/PUT-12

**Comment by rickmak** [comment]
To make the checking right, we will need a private chain deployed. Will LikeCoin side provide a test network for this purpose?

**Comment by williamchong007** [comment]
@Aludirk @nnkken

**Comment by nnkken** [comment]
Even if you build a private local network, you can't connect to that network using Trust.
For testing, you can use the Rinkeby network, which you can get Ether from https://faucet.rinkeby.io/
Both Metamask and Trust supports the Rinkeby network.

**Comment by nnkken** [comment]
Are we talking about Ethereum private chain? Or LikeChain?

**Comment by rickmak** [comment]
I am concerning on the staging LikeCion API, with reference to the workflow: https://github.com/likecoin/puttyimages-web/wiki/LoginFlow

I assume this issue will also communicate with Like.co API to query basic user info.

**Comment by nnkken** [comment]
I don't get what's the relation between login flow and Ethereum chain...

**Comment by nnkken** [comment]
The only thing like.co API needed from Metamask / Trust is the signature (on the challenge / token / secret / whatever), which does not need to connect to the Ethereum network.

**Comment by rickmak** [comment]
Agrees today on we will assume there is a metamask checking component from @nwingt in early next week.

We will do the missing metamask UI. And the Like.co API call with mock first.
